### ISSUE TITLE
environmentaldatainitiative.org squatted

### ISSUE THREAD

**Issue by alee** [earthcube/facetsearch#114]
Not sure if this is the right place to raise this but https://geocodes.earthcube.org/#/about links here to create an issue. The first link on that page (http://environmentaldatainitiative.org) appears to have been taken over by some spammy casino-ish operator... 

Looks like the link should be updated to https://edirepository.org/ instead?

![image](https://github.com/earthcube/facetsearch/assets/22534/c273414a-fffa-4593-98dc-ab4a38e0dd76)

![image](https://github.com/earthcube/facetsearch/assets/22534/cc0ec0d9-bc4f-4f02-be0a-37590023d551)

**Comment by valentinedwv** [comment]
ok, changed to edipreository.org, may take a while for it to to production instances
