### ISSUE TITLE
add version number in label

### ISSUE THREAD

**Issue by smrgeoinfo** [earthcube/facetsearch#12]
e.g. LinkedEarth/Pyleoclim_util  
https://alpha.geocodes.earthcube.org/#/dataset/urn:gleaner:milled:lipdverse:509e465d0793506b237cea8069c3cb2d276fe9c2,  search 'Norway', look at 'Svartvatnet-Norway.Seppa.2009' result'

'Pyleoclim' appears twice as a downloadable tool 
http://n2t.net/ark:/23942/g2600032  doesn't have a version property
http://n2t.net/ark:/23942/g22914 has schema:version "0.6.2"

if the schema:version is concatenated with the schema:name, the two could be differentiated; this would hopefully solve most problems.   More durable logic would check to see if there were duplicate names, then check for schema:version, if that's missing, then schema:identifier, finally @id; if those are all missing or the same, then don't show both results. 

 Better solution would be validation on resource registration to verify that the provided name is unique in the registry, but we don't have control on that.

**Comment by valentinedwv** [comment]
altName and version on the dataset cards: https://dev.geocodes.earthcube.org/#/dataset/urn:gleaner:milled:lipdverse:509e465d0793506b237cea8069c3cb2d276fe9c2

Needs to be added to tools:
https://dev.geocodes.earthcube.org/#/tool/http:%2F%2Fn2t.net%2Fark:%2F23942%2Fg2600032

Need to return schema:version in the search results... maybe
