### ISSUE TITLE
Enable configurations for subset repositories (for communities)

### ISSUE THREAD

**Issue by ylyangtw** [earthcube/facetsearch#126]

**Comment by valentinedwv** [comment]
define reports in the data()
https://github.com/earthcube/facetsearch/blob/0e4b01c29e4a798c52a97e639baef77cac30f823/client/src/components/help/about.vue#L140

also empty string ""  string1.trim().length === 0
https://github.com/earthcube/facetsearch/blob/0e4b01c29e4a798c52a97e639baef77cac30f823/client/src/components/help/about.vue#L141

[lodash includes](https://lodash.com/docs/#includes)...
 this.info = response.data.filter(item => _.includes(item.community, community) ))
 https://github.com/earthcube/facetsearch/blob/0e4b01c29e4a798c52a97e639baef77cac30f823/client/src/components/help/about.vue#L164
 
 and put the all logic in here:
.then(response => (
if (all... undefined, empty( this. info = reponse.data} 
else {
                  this.info = response.data.filter(item => item.community === community)))
                  }
