### ISSUE TITLE
Year Published Range bar is not working

### ISSUE THREAD

**Issue by ylyangtw** [earthcube/facetsearch#148]
Please see this example: https://ecoforecast.geocodes-aws.earthcube.org/#/search/?q=water+temperature&resourceType=all

- [ ] the range slider is not arrowing down the years

**Comment by valentinedwv** [comment]
Issue is with vue proxy object thing passed to component that had no idea how to handle it.
the method to handle this is to pass a toRaw(proxy)


https://chrysanthos.xyz/article/how-to-get-the-data-of-a-proxy-object-in-vue-js-3/

also can google: vue3 proxy object to array

**Comment by valentinedwv** [comment]
This is probably and issue to do with the compoent. update to a new range slider

https://www.npmjs.com/package/vue-range-multi
