### ISSUE TITLE
Dataset search on "Steens Reversal" returns only tools, not datasets

### ISSUE THREAD

**Issue by njarboe** [earthcube/facetsearch#17]
Dataset search on "Steens Reversal" returns only tools, not datasets.
![Screen Shot 2021-05-21 at 1 03 18 PM](https://user-images.githubusercontent.com/1278789/119193066-eb617d80-ba35-11eb-8c03-ac56cb3d579a.png)
![Screen Shot 2021-05-21 at 1 05 54 PM](https://user-images.githubusercontent.com/1278789/119193089-f7e5d600-ba35-11eb-9e87-c1ed993b782f.png)

Steens is also only found as keyword in one result.

**Comment by valentinedwv** [comment]
deployed 
https://beta.geocodes.earthcube.org/#/search?q=steens%20reversal&resourceType=all
