### ISSUE TITLE
open dataset in (mybinder)NoteBook

### ISSUE THREAD

**Issue by MBcode** [earthcube/facetsearch#33]
**A few groups have said they would be interested in seeing data being able to be opened in a NoteBook**
We've been chatting about this for awhile, and now need a demo of it for mid-July

**I have assumed it would be next to the download button, but open in a NB**
It would take the download-url and open a template-NB that could download that url into a dataframe.  [[This](http://mbobak-ofc.ncsa.illinois.edu/fs/landing.html) old search has a NoteBooks-link tab, that opens a jupyterhub page, but unlike colab, this needs a paswd I can not share]

**I've also heard of a more cinergi like approach**
In cinergi the NB was more like the details page, and had the ability to open any of the datasets;  DV gave me: https://github.com/CINERGI/geoportal-server-catalog/blob/22ac260cc4d92d7cdcb149876170977c967edad3/geoportal/src/main/webapp/app/search/ItemCard.js#L930 but said sending >1 download link in the url for the mybinder might be a problem

**Additional context**
I have an ecotech [thread](https://earthcube.slack.com/archives/CTHSP6PHA/p1625069790220000?thread_ts=1624050680.181700&cid=CTHSP6PHA) on all the things I've tried of late; incl [colab](https://colab.research.google.com/github/MBcode/ec/blob/master/NoteBook/colab_paste2read.ipynb), but that would mean pasting the link, which might still work.   The cinergi like work could still be done near the download (just 1 file / link) or in a NB section, we can chat about that too

**Comment by robkooper** [comment]
Potentially solution:
1. create a special container that can run a notebook and save the cells as new notebook
2. Render notebook in viewer only https://github.com/jsvine/nbpreview

**Comment by robkooper** [comment]
another option, render notebook, then push as a gist with the name of the dataset the name of the gist

github will render the gist, and this way we can make them public so people can see them as well.

**Comment by MBcode** [comment]
Looks like NoteBooks will go between web&downloadable  related-tools; 
It will be matched similarly to the other tool-matches, but probably time to generalize this,
So the RR record for a new NB-template should describe which data-md-elts it should match against;  More on this soon, after chats w/SR&DF

**Comment by MBcode** [comment]
Right now you can try a test server on the old-gui: http://mbobak-ofc.ncsa.illinois.edu/fs 
When on a details page, click on: colab-NB_links tab, and should be able to open anything
As just mentioned we will work on matching, before inserting it in the ConnectedTools section

**Comment by MBcode** [comment]
Will start w/something easy, modify/add2 the web-service matching query, if needed and make a RR entry for the 1st basic NoteBook template, so when a basic download type is there, that it suggests an instantiation of that NB; This will be 1/url right now

**Comment by MBcode** [comment]
Will start w/DV&BZ finishing [moving](http://mbobak-ofc.ncsa.illinois.edu/ext/ec/nb/db.vue) the colab-icon-button [line](https://github.com/MBcode/ec/blob/master/geodexUI/website/js/dataset2/obj-exchange.js#L546) over to next to the vue-[button](https://github.com/earthcube/facetsearch/blob/master/client/src/components/dataset/downloadfiles.vue#L10)

**Comment by MBcode** [comment]
remotes/origin/feat/binder
=I was going to say put colab icon/link near the binder1, but binder doesn't get any params, yet.
 So, till it does I'd suggest replacing it, till binder can start from the gist, or read url params.

**Comment by MBcode** [comment]
You can try it out now in [dev](dev.geocodes.earthcube.org) (open-in-colab) near the download buttons, so you can get/preview/play w/the data from the download button; the binder link still opens a template dir, but could use even earlier notes to either open the gist link, or the temp file that papermil generates before the that

**Comment by MBcode** [comment]
[dev](https://dev.geocodes.earthcube.org/) not consistent yet, but do have [pics](http://mbobak-ofc.ncsa.illinois.edu/ext/ec/nb/jul/O/nb.htm) of the buttons, from when it was being served

**Comment by MBcode** [comment]
DV started [gDoc](https://docs.google.com/document/d/1dIusvhpbJuN7HC8smPPGbn9HIWJGsN7iZafKTRTc42I/edit#heading=h.42rdooqa3nhy) on getting multiple datasets into a NB; We should rough out timelines for the stages on NB dev I've mentioned (next step matching) to more full RR descriptions to match more, incl generailzed submission; along w/other tasks, and how it fits in w/the [longer range plan](https://docs.google.com/spreadsheets/d/1yaC7TE-aM-ez0zUVhgn5CLow_65SsZI8IF-qAzzeLxo/edit#gid=0)

**Comment by MBcode** [comment]
the branch w/both versions has been on alpha but are ready to be promoted to the public site, so we can get feedback
