### ISSUE TITLE
Notebooks need to be sent urn

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/facetsearch#48]
Bobak: can still see NB not getting a URN

issue is that format needs to be encoded so any hashes (#) are encoded.
http url encoders don't encode hashes.

**Comment by valentinedwv** [comment]
https://alpha.geocodes.earthcube.org/#/dataset/urn:gleaner:milled:lipdverse:509e465d0793506b237cea8069c3cb2d276fe9c2 


"https://schema.org/encodingFormat": 
[
"application/zip" ,
"http://linked.earth/ontology/core/1.2.0/index-en.html#Dataset"
]
Link created:
http://141.142.218.86:3031/mknb?url=http://lipdverse.org/Temp12k/1_0_2/Svartvatnet-Norway.Seppa.2009.lpd&ext=application%2Fzip%20%3B%20http%3A%2F%2Flinked.earth%2Fontology%2Fcore%2F1.2.0%2Findex-en.html%23Dataset&urn=urn:gleaner:milled:lipdverse:509e465d0793506b237cea8069c3cb2d276fe9c2&


decoded:
http://141.142.218.86:3031/mknb?url=http://lipdverse.org/Temp12k/1_0_2/Svartvatnet-Norway.Seppa.2009.lpd&ext=application/zip ; http://linked.earth/ontology/core/1.2.0/index-en.html#Dataset&urn=urn:gleaner:milled:lipdverse:509e465d0793506b237cea8069c3cb2d276fe9c2&

**Comment by MBcode** [comment]
seeing w/a few lipidverse pages

**Comment by valentinedwv** [comment]
Even when I encode the hash, it gets decoded by binder.
so, encoding a hash as <hash>  and we have to do our own decoding.

https://mybinder.org/v2/gh/earthcube/NotebookTemplates.git/geocodes_template?urlpath=notebooks/template.ipynb?dataset={%22contenturl%22:%22http://lipdverse.org/Temp12k/1_0_2/Svartvatnet-Norway.Seppa.2009.lpd%22,%22ext%22:%22application%2Fzip%20%3B%20http%3A%2F%2Flinked.earth%2Fontology%2Fcore%2F1.2.0%2Findex-en.html%23Dataset%22,%22urn%22:%22urn:gleaner:milled:lipdverse:509e465d0793506b237cea8069c3cb2d276fe9c2%22}&nb=

https://mybinder.org/v2/gh/earthcube/NotebookTemplates.git/geocodes_template?urlpath=notebooks/template.ipynb?dataset={%22contenturl%22:%22http://lipdverse.org/Temp12k/1_0_2/Svartvatnet-Norway.Seppa.2009.lpd%22,%22ext%22:%22application%2Fzip%20%3B%20http%3A%2F%2Flinked.earth%2Fontology%2Fcore%2F1.2.0%2Findex-en.html%26%2335%3BDataset%22,%22urn%22:%22urn:gleaner:milled:lipdverse:509e465d0793506b237cea8069c3cb2d276fe9c2%22}&nb=

**Comment by valentinedwv** [comment]
Link that's sent to mknb service: 
http://141.142.218.86:3031/mknb?url=http://lipdverse.org/Temp12k/1_0_2/Svartvatnet-Norway.Seppa.2009.lpd&ext=application%2Fzip%20%3B%20http%3A%2F%2Flinked.earth%2Fontology%2Fcore%2F1.2.0%2Findex-en.html%3Chash%3EDataset&urn=urn:gleaner:milled:lipdverse:509e465d0793506b237cea8069c3cb2d276fe9c2&

Binder can now receive the ext.

**Comment by valentinedwv** [comment]
mknb service needs to handle ext parameter, or we remove the parameter from the link

**Comment by valentinedwv** [comment]
semicolon confusing some code down the line...
'application/zip ; http://linked.earth/ontology/core/1.2.0/index-en.html<hash>Dataset'
becomes:
'application/zip_'

Is there any reason why the mknb code is not just using url encoding for the passed parameters?
https://www.urlencoder.io/python/

'application/zip ; http://linked.earth/ontology/core/1.2.0/index-en.html<hash>Dataset'
becomes:
'application/zip%20%3B%20http%3A//linked.earth/ontology/core/1.2.0/index-en.html%3Chash%3EDataset'

**Comment by MBcode** [comment]
'ext' is searched via regex, because it can vary a bit, so 1 extra char won't make a difference w/in the utils in the NoteBook. ;will go2proper urlencode soon though to handle more cases

**Comment by MBcode** [comment]
since I only wanted the 1st arg/part of 'ext', I'm selecting only that for now, &it works for these again

**Comment by MBcode** [comment]
Still could use the 'ext' sent into the binder NoteBooks, even though I have a stopgap for getting it from the urn
