### ISSUE TITLE
change SPARQL link in upper right to open Sparql Notebook

### ISSUE THREAD

**Issue by smrgeoinfo** [earthcube/facetsearch#73]
The SPARQL link in upper right corner at https://geocodes.earthcube.org/ currently opens a YASGUI interface on the Blazegraph triple store with the dataset metadata.  
Request is to change that link to open the SPARQL notebook Mike B has been working on that gives the user programmatic control of constructing queries and filtering results. 
The notebook template needs to be moved into GitHub https://github.com/earthcube/NotebookTemplates repo and made ready for production. Template is athttps://github.com/MBcode/ec/blob/master/NoteBook/sparql.ipynb (no papermill parameters injected)
The button would run code currently at https://github.com/MBcode/ec/blob/master/NoteBook/mknb.py#L241; call this code with the text used for the current GeoCODES query state, generates notebook from the Sparql notebook template and opens in Collab for user. mknb code needs to be moved to production Github repo for GeoCODES.  Example call from old GeoCODES GUI: `const mkQ = 'http://141.142.218.86:3031/mkQ/?q=' + q;`

**Comment by MBcode** [comment]
mknb.py's mkQ route works like this: http://141.142.218.86:3031/mkQ/?q=water & giving: https://colab.research.google.com/gist/MBcode/6841282b1d78f9941b02c9b5b1896c43/water.ipynb
