### ISSUE TITLE
Collection UI

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/facetsearch#81]
Add Collection menu to replace 'Stored Dataset' on results page 

No confirm button on results page, when collection is selected, add item to collection

Need to have menu item to add new collection.

On results load, show what collections an item is stored in the collection menu

**Comment by smrgeoinfo** [comment]
Goal is to enable user to pick search results and add to a 'collection'. 

- User can make new collections, give them a name. 
- User can add a selected search result to one or more existing collections, or start a new one
- user can recall and view all search results in an of their collections
- User can send a URL to another user to share a collection, when they GET the url, GeoCODES opens (in browser) and they see the collection results.

**Comment by valentinedwv** [comment]
images from figma:
![Search](https://user-images.githubusercontent.com/851784/163595918-1da93e37-d49b-4c2b-a63b-5d73ca066789.png)
![Collection](https://user-images.githubusercontent.com/851784/163595931-cadc3f49-3e96-4528-a90f-d124235cc632.png)
